### ISSUE TITLE
Any plan for `rem`

### ISSUE THREAD

**Issue by jieyou** [xcatliu/mobi.css#30]
`rem` layout is a popular and modern way to deal with mobile pages layout.
Is there any plan to support it?

**Comment by xcatliu** [comment]
Actually Mobi.css support `rem` now:

You can checkout the [`_reset.scss`](https://github.com/xcatliu/mobi.css/blob/master/src/_resets.scss) and [`_variables.scss`](https://github.com/xcatliu/mobi.css/blob/master/src/_variables.scss#L93)

``` css
html {
  font-size: 10px;
}

body {
  font-size: 1.8rem;
}
```

But I kept some `margin`s and `padding`s using `px`:

``` css
mt-30 {
  margin-top: 30px;
}
```
