### ISSUE TITLE
Add `text-muted` class

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/mobi.css#62]
``` scss
.text-muted {
  color: $color-text-muted;
}

a.text-muted {
  color: $color-text-muted;
  text-decoration: underline;
}
```
